[toolchain]
channel = "nightly"
components = ["rustc", "cargo", "rust-std", "rust-src", "rust-analyzer", "clippy", "rustfmt"]
targets = ["x86_64-pc-windows-msvc", "aarch64-apple-ios", "aarch64-linux-android"]
