[package]
name = "overlay"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "overlay"
path = "main.rs"

[dependencies]
util = { path = "../util" }

[dependencies.craft]
path = "../../crates/craft"
default-features = false
features = ["vello_renderer", "devtools"]
package = "craft_gui"
