[package]
name = "counter"
version = "0.1.0"
edition = "2024"
default-run = "counter"

[[bin]]
name = "counter"
path = "main.rs"

[dependencies]
util = { path = "../util" }

[dependencies.retgui]
path = "../../crates/retgui"
default-features = false

[dependencies.retgui_retained]
path = "../../crates/retgui_retained"
default-features = false
features = ["system_fonts"]

[target.'cfg(not(target_os = "android"))'.dependencies.retgui_renderer]
path = "../../crates/retgui_renderer"
features = ["vello_hybrid_renderer"]
