[package]
name = "accordion"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "accordion"
path = "main.rs"

[dependencies]
craft = { path = "../../crates/craft", default-features = false, features = ["vello_renderer", "devtools"] }
util = { path = "../util" }