[package]
name = "retgui_calendar"
version = "0.1.0"
edition.workspace = true

[dependencies]
sys-locale = "0.3.2"

icu_calendar = { version = "2.2", features = ["alloc"] }
icu_datetime = "2.2"
icu_locale = "2.2"

jiff.workspace = true

[target.'cfg(windows)'.dependencies]

[target.'cfg(windows)'.dependencies.windows]
workspace = true
features = [
    "Win32_Globalization",
]

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
web-sys = { version = "0.3.103", features = ["Window", "Navigator"] }
