[package]
name = "syntect_dumper"
version = "0.1.0"
edition.workspace = true

[dependencies]

[dependencies.reqwest]
workspace = true
features = ["blocking"]

[target.'cfg(not(target_os = "android"))'.dependencies.reqwest]
workspace = true
features = ["native-tls"]

[target.'cfg(target_os = "android")'.dependencies.reqwest]
workspace = true
features = ["rustls"]

[dependencies.syntect]
workspace = true
features = ["dump-create", "yaml-load", "plist-load", "regex-fancy"]

[[bin]]
name = "syntect-dumper"
path = "src/main.rs"
