[package]
name = "retgui"
description = "Core library for the RetGui GUI framework."
version = "0.1.1"
edition = "2024"
resolver = "2"
license-file = "LICENSE"
homepage = "https://retguigui.com/"
repository = "https://github.com/RetGui/retgui"

[features]
audio = ["dep:maudio", "dep:windows"]
dynamic_linking = []
integration_tests = ["vello_cpu_renderer", "png"]
clipboard = ["dep:clipboard-rs"]
vello_cpu_renderer = ["retgui_renderer/vello_cpu_renderer"]
vello_hybrid_renderer = ["retgui_renderer/vello_hybrid_renderer"]
http_client = ["retgui_resource_manager/http_client"]

system_fonts = ["parley/system"]

png = ["image/png"]
jpeg = ["image/jpeg"]

markdown = ["dep:pulldown-cmark", "code_highlighting", "http_client", "link"]
code_highlighting = ["dep:syntect"]
link = ["dep:open"]

default = ["vello_hybrid_renderer", "clipboard"]

[dependencies]
retgui_logging = { path = "../logger", version = "0.1.0" }
retgui_undo = {path = "../undo", version = "0.1.1"}
retgui_calendar = {path = "../calendar", version = "0.1.0"}

smol_str = "0.3.6"

[target.'cfg(windows)'.dependencies.windows]
workspace = true
default-features = false
optional = true


[dependencies.issho]
git = "https://github.com/RetGui/issho.git"
rev = "b5d4fd22ef2f31013c7ea1218dd552d2768a4566"

[dependencies.bitflags]
version = "2.10.0"
features = ["std"]

#[dependencies.kurbo]
#workspace = true

[dependencies.smallvec]
version = "1.15.1"
default-features = false

[dependencies.peniko]
workspace = true

[dependencies.tinyvg-rs]
workspace = true

[dependencies.rustc-hash]
version = "2.1.1"
default-features = false
features = ["std"]

[target.'cfg(any(target_os = "windows", target_os = "macos", target_os = "linux"))'.dependencies.clipboard-rs]
version = "0.3.1"
optional = true

[dependencies.pulldown-cmark]
version = "0.13.4"
default-features = false
features = []
optional = true

[dependencies.syntect]
workspace = true
features = ["default-fancy", "parsing", "dump-load", "default-themes"]
optional = true

[dependencies.image]
workspace = true

[dependencies.gummy]
version = "0.12.1"
git = "https://github.com/RetGui/gummy"
rev = "08e18fdf278df0e8270e12ad60dc4b8519c072e8"
default-features = false
features = ["std", "gummy_tree", "flexbox", "content_size", "block_layout"]

[dependencies.jiff]
workspace = true

[target.'cfg(not(target_os = "android"))'.dependencies.winit]
workspace = true
features = []

[target.'cfg(target_os = "android")'.dependencies.winit]
workspace = true
features = ["android-native-activity"]

[dependencies.parley]
git = "https://github.com/linebender/parley.git"
rev = "a0752c7bdc3ad88dac19fc194d2b8e57e59bea2e"
default-features = false
features = ["std"]

[target.'cfg(target_arch = "wasm32")'.dependencies.web-time]
version = "1.1.0"
default-features = false
features = []

[target.'cfg(target_arch = "wasm32")'.dependencies.wasm-bindgen]
version = "0.2.126"
default-features = false
features = ["std", "msrv"]

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.103"
default-features = false
features = [
    "Document",
    "Window",
    "Element",
]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.open]
version = "5.3.3"
default-features = false
optional = true
features = []

[dependencies.retgui_primitives]
path = "../primitives"
default-features = false
version = "0.1.1"

[dependencies.retgui_renderer]
path = "../renderer"
default-features = false
version = "0.1.1"

[dependencies.retgui_runtime]
path = "../runtime"
default-features = false
version = "0.1.1"

[dependencies.retgui_resource_manager]
path = "../resource_manager"
default-features = false
version = "0.1.1"

[dependencies.maudio]
git = "https://github.com/someotherself/maudio.git"
rev = "e787d754e96dd1d548e2c79c37a40dfc213995df"
optional = true

[[test]]
name = "counter"
path = "tests/counter.rs"
required-features = ["integration_tests"]

[[test]]
name = "text_input"
path = "tests/text_input.rs"
required-features = ["integration_tests"]

[[test]]
name = "radio"
path = "tests/radio.rs"
required-features = ["integration_tests"]
