[package]
name = "oku_core"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]

winit = { git = "https://github.com/rust-windowing/winit", rev = "34c15608e073a75c5e56fdb0a4df629ef14e6c9c" }
tiny-skia = { git = "https://github.com/RazrFalcon/tiny-skia", rev = "784569522f728cc70232cbb88abd7330571b51dd" }
softbuffer = { git = "https://github.com/rust-windowing/softbuffer", rev = "d80ef86fa7aa832298f3d85f0243ace3e3f9d7a3" }
cosmic-text = { git = "https://github.com/pop-os/cosmic-text", rev = "24fb2089532f6711f2edf67fadaf4b99375de2e4" }
taffy = { git = "https://github.com/DioxusLabs/taffy", rev = "e363fc8065ce370dba9fcacd1bd6575e65657c74" }
accesskit = "0.15.0"
#accesskit_winit = { version = "0.18.0" }

log = "0.4.21"
dyn-clone = "1.0.17"

# https://crates.io/crates/glam
# SSE2 is enabled by default on x86_64 targets.
glam = { version = "0.28.0" }
env_logger = { version = "0.11.3" }
wgpu = { git = "https://github.com/gfx-rs/wgpu", rev = "e78c33b3099474c272e9c0f2c61dc3db10fca269" }
bytemuck = { version = "1.16.0", features = ["derive"] }
image = { version = "0.25.1", default-features = false, features = ["png", "jpeg"] }

cfg-if = "1.0.0"
once_cell = "1.19.0"
slotmap = "1.0.7"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
web-sys = { version = "0.3.69", features = [
    "Document",
    "Window",
    "Element",
] }
console_log = "1.0"
#wgpu = { version = "0.19.3", features = ["webgpu"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.38.0", features = ["full"] }

[features]
dynamic_linking = []
