[package]
name = "oku_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
winit = { git = "https://github.com/rust-windowing/winit", rev = "990bbf178f9ddc52ec75026e357fe54853bf533f" }
tiny-skia = "0.11.4"
softbuffer = "0.4.1"
cosmic-text = { git = "https://github.com/pop-os/cosmic-text", rev = "2766961af621b9235616e186046f6d14a2f5fbc0" }
taffy = { git = "https://github.com/DioxusLabs/taffy", rev = "bb3ec967e6c386d9d9060010806d65201393a398" }
accesskit = "0.12.2"
#accesskit_winit = { version = "0.18.0" }

tokio = { version = "1.36.0", features = ["full"] }