[package]
name = "oku_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
winit = { git = "https://github.com/rust-windowing/winit", rev = "944347696ab965d9dc5b617fc89daa9f7ad1ea88" }
tiny-skia = "0.11.4"
softbuffer = "0.4.1"
cosmic-text = { git = "https://github.com/pop-os/cosmic-text", rev = "22e61965aa38ab0bd64bbdddf3848ae891edceba" }
taffy = { git = "https://github.com/DioxusLabs/taffy", rev = "bb3ec967e6c386d9d9060010806d65201393a398" }
accesskit = "0.12.2"
#accesskit_winit = { version = "0.18.0" }

tokio = { version = "1.36.0", features = ["full"] }

# https://crates.io/crates/glam
# SSE2 is enabled by default on x86_64 targets.
glam = { version = "0.25.0" }
env_logger = { version = "0.11" }
wgpu = { version = "0.19.3" }

[features]
dynamic_linking = []
