[package]
name = "oku_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
winit = "0.29.10"
tiny-skia = "0.11.4"
softbuffer = "0.4.1"
cosmic-text = {git = "https://github.com/pop-os/cosmic-text", rev = "0cb6eba6e708e2743313ee0016162de7a0146353"}
taffy = {git = "https://github.com/DioxusLabs/taffy", rev = "16823d17d0953ce30d0d4d733dc33c830b29a647"}
rand = "0.8.5"
accesskit = "0.12.2"
accesskit_winit = {version = "0.18.0"}

tokio = { version = "1.35.1", features = ["full"] }