[package]
name = "oku_core"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]

winit = { git = "https://github.com/rust-windowing/winit", rev = "3e8fa410735cfb1486b6f7fd636c810fffd6c268" }
tiny-skia = { git = "https://github.com/RazrFalcon/tiny-skia", rev = "9b673e6c14e5e0c3f98413f8fa7e3a6cb315183b" }
softbuffer = { git = "https://github.com/rust-windowing/softbuffer", rev = "af8c5a7ea5d68ef539ac0b4546ebbd9e482e1e71" }
cosmic-text = { git = "https://github.com/pop-os/cosmic-text", rev = "2f5f2c63dabc0173adaa95d619a777454a3c39af" }
taffy = { git = "https://github.com/DioxusLabs/taffy", rev = "bad7c40773bcf82edf575964ff20cb1557f8c285" }
accesskit = "0.13.0"
#accesskit_winit = { version = "0.18.0" }

log = "0.4.21"

# https://crates.io/crates/glam
# SSE2 is enabled by default on x86_64 targets.
glam = { version = "0.28.0" }
env_logger = { version = "0.11.3" }
wgpu = { git = "https://github.com/gfx-rs/wgpu", rev = "7fc7f58280bf745c93bca373d4f21f71db904f0c" }
bytemuck = { version = "1.16.0", features = ["derive"] }
image = { version = "0.25.1", default-features = false, features = ["png", "jpeg"] }

cfg-if = "1.0.0"
once_cell = "1.19.0"
slotmap = "1.0.7"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
web-sys = { version = "0.3.69", features = [
    "Document",
    "Window",
    "Element",
] }
console_log = "1.0"
#wgpu = { version = "0.19.3", features = ["webgpu"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.38.0", features = ["full"] }

[features]
dynamic_linking = []
