[package]
name = "website"
version = "0.1.0"
edition = "2021"

[dependencies]

oku = { path = "../", features = ["wgpu_renderer"] }

tracing-subscriber = "0.3.19"
tracing = "0.1.41"

serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.133"

[target.'cfg(target_arch = "wasm32")'.dependencies]
tracing-web = "0.1.3"
console_error_panic_hook = "0.1.7"

[dependencies.reqwest]
version = "0.12.12"
default-features = false
features = ["rustls-tls", "json"]


# binary
[[bin]]
name = "website"
path = "src/lib.rs"