[package]
name = "gallery"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gallery"
path = "main.rs"

[features]
audio = ["retgui_retained/audio"]
default = ["audio"]

[dependencies]
serde = { version = "1", features = ["derive"] }
util = { path = "../util" }

[dependencies.reqwest]
workspace = true
default-features = false
features = ["json", "rustls"]

[dependencies.retgui_retained]
path = "../../crates/retgui_retained"
default-features = false
features = [
    "system_fonts",
    "http_client",
    "jpeg",
    "png",
    "clipboard",
    "vello_hybrid_renderer"
]
