[package]
name = "tour"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tour"
path = "main.rs"

[dependencies]
util = { path = "../util" }

[dependencies.craft]
path = "../../crates/craft"
features = ["vello_renderer", "devtools"]
default-features = false
package = "craft_gui"