[package]
name = "tour"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tour"
path = "main.rs"

[dependencies]
craft = { path = "../../", features = ["vello_hybrid_renderer"], default-features = false }
util = { path = "../util" }