name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Oku
      run: cargo build --verbose
    - name: Build Counter Example
      run: cargo build --example counter
    - name: Build Request Example
      run: cargo build --example request
    - name: Build Text Example
      run: cargo build --example text
    #- name: Run tests
    #  run: cargo test --verbose
