[package]
name = "text"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "text"
path = "main.rs"

[dependencies]
util = { path = "../util" }

[dependencies.craft]
path = "../../crates/craft"
default-features = false
features = ["vello_renderer", "devtools", "http_client"]
package = "craft_gui"
