[package]
name = "syntect_dumper"
version = "0.1.0"
edition.workspace = true

[dependencies]

[dependencies.reqwest]
version = "0.12.20"
features = ["blocking"]

[dependencies.syntect]
version = "5.2.0"
features = ["dump-create"]

[[bin]]
name = "syntect-dumper"
path = "src/main.rs"